### ISSUE TITLE
a fresh install "npm run dev" is resulting in "window is not defined" error

### ISSUE THREAD

**Issue by gajus** [CrocoDillon/universal-react-redux-boilerplate#11]
``` sh
$ export DEBUG=*,-babel
$ npm run dev

> universal-react-redux-boilerplate@2.0.0 dev /Users/gajuskuizinas/Documents/dev/temp3
> node ./bin/server

  koa:application use - +0ms
  koa:application use - +1ms
  koa:application use - +1ms
  koa:application listen +0ms
Server is running!
Hash: eb9bd0b1d3a0d2c94363
Version: webpack 2.1.0-beta.21
Time: 3016ms
 Asset     Size  Chunks             Chunk Names
app.js  3.16 MB       0  [emitted]  app
webpack built eb9bd0b1d3a0d2c94363 in 3016ms

  ReferenceError: window is not defined
      at supportsPopstateOnHashchange (/temp/node_modules/history/lib/DOMUtils.js:39:10)
      at Object.<anonymous> (/temp/node_modules/history/lib/BrowserProtocol.js:17:75)
      at Module._compile (module.js:556:32)
      at Module._extensions..js (module.js:565:10)
      at Object.require.extensions.(anonymous function) [as .js] (/temp/node_modules/babel-register/lib/node.js:154:7)
      at Module.load (module.js:473:32)
      at tryModuleLoad (module.js:432:12)
      at Function.Module._load (module.js:424:3)
      at Module.require (module.js:483:17)
      at require (internal/module.js:20:19)


  ReferenceError: window is not defined
      at supportsPopstateOnHashchange (/temp/node_modules/history/lib/DOMUtils.js:39:10)
      at Object.<anonymous> (/temp/node_modules/history/lib/BrowserProtocol.js:17:75)
      at Module._compile (module.js:556:32)
      at Module._extensions..js (module.js:565:10)
      at Object.require.extensions.(anonymous function) [as .js] (/temp/node_modules/babel-register/lib/node.js:154:7)
      at Module.load (module.js:473:32)
      at tryModuleLoad (module.js:432:12)
      at Function.Module._load (module.js:424:3)
      at Module.require (module.js:483:17)
      at require (internal/module.js:20:19)
```

**Comment by CrocoDillon** [comment]
Hello, I just did a fresh install and cannot reproduce this issue. Maybe it's already fixed (by accident) by some recent commits :sweat_smile:

Otherwise I'm gonna need some more info. Specifically what OS and steps to reproduce.

[`universal-react-redux-boilerplate/search?q=window`](https://github.com/CrocoDillon/universal-react-redux-boilerplate/search?utf8=%E2%9C%93&q=window)

**Comment by CrocoDillon** [comment]
I'm just gonna assume this is already fixed, let me know otherwise :grin:
